ML Test Pistachio

In [24]:
using Pkg
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("StatsBase")
Pkg.add("MLJ")
Pkg.add("ProgressBars")
Pkg.add("LinearAlgebra")
#Pkg.add("Threads")

using Statistics,DataFrames, CSV
using StatsBase
using MLJ
using ProgressBars
using LinearAlgebra
using Base.Threads

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes 

to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`


   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`

   Resolving package versions...


  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\asanche2\.julia\environments\v1.8\Manifest.toml`


We want to read in the pistachio data using csv and dataframes

In [2]:
data = CSV.read("../../testing-data/pistachio_class/pistachio.csv",DataFrame)

1718×17 DataFrame
  Row │ AREA    PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY  EQDIASQ  SOLI ⋯
      │ Int64   Float64    Float64     Float64     Float64       Float64  Floa ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │  73107   1161.81      442.407     217.726        0.8705  305.095    0. ⋯
    2 │  89272   1173.18      460.255     251.955        0.8369  337.142    0.
    3 │  60955    999.789     386.925     209.125        0.8414  278.586    0.
    4 │  79537   1439.51      466.797     221.214        0.8806  318.229    0.
    5 │  96395   1352.67      515.873     246.595        0.8784  350.334    0. ⋯
    6 │  74065   1380.55      405.432     245.229        0.7963  307.087    0.
    7 │  91533   1915.96      451.737     267.927        0.8051  341.385    0.
    8 │  77803   2034.99      455.435     270.371        0.8047  314.741    0.
  ⋮   │   ⋮         ⋮          ⋮           ⋮            ⋮           ⋮        ⋮ ⋱
 1712 │  70937   1149.48      432.704     217.639        0.8643  300.533    0. ⋯
 1713 │  84808   1248.86      483.301     235.874        0.8728  328.604    0.
 1714 │  65570   2071.45      418.026     217.146        0.8545  288.94     0.
 1715 │  68849   1441.26      451.046     205.255        0.8905  296.076    0.
 1716 │  90270   1370.54      428.964     269.823        0.7774  339.021    0. ⋯
 1717 │  73148   1309.84      469.049     208.314        0.896   305.18     0.
 1718 │  78780   1324.88      451.591     239.302        0.8481  316.711    0.
                                                11 columns and 1703 rows omitted

In [3]:
describe(data)

17×7 DataFrame
 Row │ variable       mean        min                median   max              ⋯
     │ Symbol         Union…      Any                Union…   Any              ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ AREA           79872.0     29808              79795.0  124008           ⋯
   2 │ PERIMETER      1421.8      858.363            1260.79  2755.05
   3 │ MAJOR_AXIS     446.206     321.425            448.453  535.642
   4 │ MINOR_AXIS     238.193     133.51             235.889  383.046
   5 │ ECCENTRICITY   0.840347    0.5049             0.85025  0.946            ⋯
   6 │ EQDIASQ        317.79      194.815            318.745  397.356
   7 │ SOLIDITY       0.940103    0.588              0.9538   0.9951
   8 │ CONVEX_AREA    84947.7     37935              84973.0  132478
  ⋮  │       ⋮            ⋮               ⋮             ⋮           ⋮          ⋱
  11 │ ROUNDNESS      0.570831    0.0628             0.64385  0.9336           ⋯
  12 │ COMPACTNESS    0.712841    0.476              0.70975  0.8695
  13 │ SHAPEFACTOR_1  0.00570413  0.004              0.0056   0.0131
  14 │ SHAPEFACTOR_2  0.00301711  0.0024             0.003    0.0053
  15 │ SHAPEFACTOR_3  0.510097    0.2266             0.50375  0.7561           ⋯
  16 │ SHAPEFACTOR_4  0.955185    0.6204             0.9728   0.999
  17 │ Class                      Kirmizi_Pistachio           Siit_Pistachio
                                                    2 columns and 2 rows omitted

Need to get data in correct format

In [3]:
data_treet = data
data_treet.Class = Int32.(replace(data_treet.Class,"Siit_Pistachio"=>1,"Kirmizi_Pistachio"=>0))

1718-element Vector{Int32}:
 0
 1
 0
 0
 0
 0
 1
 0
 1
 0
 ⋮
 0
 1
 0
 1
 0
 0
 1
 0
 1

In [43]:
data_select = select(data_treet,[:"ASPECT_RATIO",:"MINOR_AXIS",:"AREA",:"Class"])
data_select_norm = mapcols(zscore, data_select[!,Not("Class")])
data_select_norm[!,:Class] = data_select[!,:Class]
data_select_norm

1718×4 DataFrame
  Row │ ASPECT_RATIO  MINOR_AXIS  AREA        Class 
      │ Float64       Float64     Float64     Int32 
──────┼─────────────────────────────────────────────
    1 │    0.549456   -0.672672   -0.521656       0
    2 │   -0.301102    0.452287    0.724853       1
    3 │   -0.203694   -0.955341   -1.45872        0
    4 │    0.874011   -0.558052   -0.0258288      0
    5 │    0.798572    0.276121    1.27412        0
    6 │   -1.01985     0.231229   -0.447783       0
    7 │   -0.884307    0.977225    0.899202       1
    8 │   -0.890524    1.05757    -0.15954        0
  ⋮   │      ⋮            ⋮           ⋮         ⋮
 1712 │    0.368319   -0.675532   -0.688989       0
 1713 │    0.620336   -0.0762372   0.380627       1
 1714 │    0.106768   -0.691745   -1.10285        0
 1715 │    1.23587    -1.08254    -0.849998       0
 1716 │   -1.28306     1.03956     0.80181        1
 1717 │    1.46012    -0.982009   -0.518495       0
 1718 │   -0.050743    0.0364312  -0.0842022      1
                                   1703 rows omitted

In [45]:
train,test = partition(data_select_norm, 0.8, shuffle=true);

In [46]:
train_in = Matrix(train[!,Not("Class")])
n_points,dim = size(train_in)
train_target = Array(train[!,"Class"])
train_target = hcat(train_target,zeros(length(train_target),dim-1))

test_in = Matrix(test[!,Not("Class")])
test_target = Array(test[!,"Class"])
test_target = hcat(test_target,zeros(length(test_target),dim-1))

print(size(train_in))
print(size(train_target))

print(size(test_in))
print(size(test_target))


(1374, 3)(1374, 3)(344, 3)(344, 3)

In [35]:
include("TransformM.jl")
using .TransformM

In [47]:
tf = TransformM.Transform_Const(dim,train_in,train_target)

Main.TransformM.Transform(3, [0.8549442309710944 -1.006917759814742 -0.8321076683093189; -1.8430502950709846 1.6799061387821033 0.6353261296954579; … ; -0.7437905803584954 0.7077583953848645 0.7580878010787266; 0.9179485585111772 0.06957671168391873 1.1050900129032928], [0.0 0.0 0.0; 1.0 0.0 0.0; … ; 1.0 0.0 0.0; 0.0 0.0 0.0], 3, Triangulation of 1374 vertices in 3 dimensions
Coordinates of vertices:
    [0.8549442309710944 -1.006917759814742 -0.8321076683093189; -1.8430502950709846 1.6799061387821033 0.6353261296954579; … ; -0.7437905803584954 0.7077583953848645 0.7580878010787266; 0.9179485585111772 0.06957671168391873 1.1050900129032928]
Indices of simplices:
    [891 87 1129 261; 1364 87 1129 1088; … ; 1175 179 193 157; 1175 471 179 193]
Lookup array from vertices to some containing simplex:
    [4225, 1125, 4167, 3851, 746, 258, 787, 3466, 1708, 3772  …  663, 5371, 7222, 818, 2882, 1311, 878, 2037, 5029, 3711]
Indices of facets of convex hull of the vertices:
    [1065 1082 886; 9

In [117]:
test_in[1,:]

3-element Vector{Float64}:
  0.7981574357540463
 -0.15587847916622483
  0.7741391679121439

In [10]:
TransformM.map_point(tf,test_in[1,:])

3-element Vector{Float64}:
 -0.5271104784716698
  0.0
  0.0

In [149]:
Transpose(test_in[1,:])

1×3 transpose(::Vector{Float64}) with eltype Float64:
 0.798157  -0.155878  0.774139

In [40]:
pred_values = zeros(0)
preds = zeros(0)
npreds = size(test_target,1)
npreds = 200
#for i in ProgressBar(1:npreds)
for i in 1:npreds
    test_i_val = test_in[i,:]
    pred_i_array = TransformM.map_point(tf,test_in[i,:])
    pred_i_val = pred_i_array[1]

    pred_i=0
    if pred_i_val>0
        pred_i=1
    end

    append!(pred_values,pred_i_val)
    append!(preds,pred_i)

    #print("Pred: $i/$npreds \r")
    #flush(stdout)
    #print("Pred: $i/$npreds")
    #print("\e[2K") # clear whole line
    #print("\e[1G") # move cursor to column 1
end
frac_correct = sum(abs.(-preds.-test_target[1:npreds,1].+1))/npreds



0.8

In [49]:

npreds = size(test_target,1)
pred_values = Vector{Float64}(undef, npreds)
preds = Vector{Int}(undef, npreds)
#for i in ProgressBar(1:npreds)
Threads.@threads for i in 1:npreds
    test_i_val = test_in[i,:]
    pred_i_array = TransformM.map_point(tf,test_in[i,:],false)
    pred_i_val = pred_i_array[1]

    pred_i=0
    if pred_i_val>0
        pred_i=1
    end

    pred_values[i] = pred_i_val
    preds[i] = pred_i

    #print("Pred: $i/$npreds \r")
    #flush(stdout)
    #print("Pred: $i/$npreds")
    #print("\e[2K") # clear whole line
    #print("\e[1G") # move cursor to column 1
end
frac_correct = sum(abs.(-preds.-test_target[1:npreds,1].+1))/npreds

0.7819767441860465

In [20]:
frac_correct = sum(abs.(-preds.-test_target[1:npreds,1].+1))/npreds

0.7592233009708738

In [14]:
Threads.nthreads()

16

All in one

In [52]:
include("TransformM.jl")
using .TransformM

In [55]:
data_select = select(data_treet,[:"ASPECT_RATIO",:"MINOR_AXIS",:"AREA",:"PERIMETER",:"ECCENTRICITY",:"CONVEX_AREA",:"Class"])
data_select_norm = mapcols(zscore, data_select[!,Not("Class")])
data_select_norm[!,:Class] = data_select[!,:Class]

train,test = partition(data_select_norm, 0.8, shuffle=true);

train_in = Matrix(train[!,Not("Class")])
n_points,dim = size(train_in)
train_target = Array(train[!,"Class"])
train_target = hcat(train_target,zeros(length(train_target),dim-1))

test_in = Matrix(test[!,Not("Class")])
test_target = Array(test[!,"Class"])
test_target = hcat(test_target,zeros(length(test_target),dim-1))

println("Train Size: ",size(train_in))
println("Test Size: ",size(test_in,1))

tf = TransformM.Transform_Const(dim,train_in,train_target)

npreds = size(test_target,1)
pred_values = Vector{Float64}(undef, npreds)
preds = Vector{Int}(undef, npreds)
#for i in ProgressBar(1:npreds)
Threads.@threads for i in 1:npreds
    test_i_val = test_in[i,:]
    pred_i_array = TransformM.map_point(tf,test_in[i,:],false)
    pred_i_val = pred_i_array[1]

    pred_i=0
    if pred_i_val>0
        pred_i=1
    end

    pred_values[i] = pred_i_val
    preds[i] = pred_i

    #print("Pred: $i/$npreds \r")
    #flush(stdout)
    #print("Pred: $i/$npreds")
    #print("\e[2K") # clear whole line
    #print("\e[1G") # move cursor to column 1
end
frac_correct = sum(abs.(-preds.-test_target[1:npreds,1].+1))/npreds

MethodError: MethodError: no method matching -(::String, ::String)
Closest candidates are:
  -(!Matched::ChainRulesCore.AbstractThunk, ::Any) at C:\Users\asanche2\.julia\packages\ChainRulesCore\7MWx2\src\tangent_types\thunks.jl:34
  -(!Matched::PyCall.PyObject, ::Any) at C:\Users\asanche2\.julia\packages\PyCall\ilqDX\src\pyoperators.jl:13
  -(!Matched::ChainRulesCore.ZeroTangent, ::Any) at C:\Users\asanche2\.julia\packages\ChainRulesCore\7MWx2\src\tangent_arithmetic.jl:101
  ...